In [1]:
import torch

In [4]:
from torch.autograd import Variable
a = Variable(torch.Tensor([[1,2],[3,4]]),requires_grad = True)

In [5]:
a

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)

In [6]:
y = torch.sum(a**2)
y

tensor(30., grad_fn=<SumBackward0>)

In [7]:
y.backward()

In [8]:
print(a.grad)

tensor([[2., 4.],
        [6., 8.]])


In [9]:
print(a.T)

tensor([[1., 3.],
        [2., 4.]], grad_fn=<PermuteBackward0>)


In [ ]:
b = Variable(torch.Tensor([[2,4],[8,10]]),requires_grad = True)
b|